[profile.default]
src = "src"
out = 'foundry-out'
libs = ["lib"]
via_ir = true
optimizer_runs = 30_000
ffi = true
fs_permissions = [
    { access = "read-write", path = ".forge-snapshots/" },
    { access = "read", path = "./test/bin/" },
]
solc_version = '0.8.26'
evm_version = "cancun"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
